export const aboutContent = {
  en: {
    label: "About Sahayak", back: "Get help", title: "The portal has a status.\nYou need a next step.",
    intro: "A scholarship says released. The bank account is still empty. Who do you ask, what do you take, and what happens if they send you somewhere else?",
    principle: "Don’t replace the desks. Replace the walking.",
    problem: "You should not have to connect the whole system yourself.",
    problemBody: "Public services often stretch across a portal, a bank and an office. Each tells you one part. Sahayak brings the next action, preparation and follow-up into one place, so you can approach the next desk with a clear question.",
    example: "An example, not a payment claim", exampleTitle: "“My scholarship says released, but the money hasn’t arrived.”",
    steps: [
      {title: "Find out what the status actually means", body: "Get help finding the payment message. You do not need to know what PFMS means or already have an office response to begin."},
      {title: "Go prepared", body: "See where to ask, what to carry, what to say and which acknowledgement to collect. Ask Sahayak to explain anything unclear."},
      {title: "Bring back the answer—even when it is a setback", body: "Record the actual response, date and reference. A supported setback, such as a reported NPCI mapping issue, opens the relevant recovery step."},
      {title: "Keep your place and your evidence", body: "Return in the same browser to continue. Keep a portable step brief and useful documents. A saved response or generated draft does not mean the money arrived."},
    ],
    try: "Find my next step", tryNote: "On the home screen, choose “Scholarship money hasn’t arrived” or describe your problem.",
    trustLabel: "How guidance earns trust", trustTitle: "Experience can improve a journey. It cannot approve itself.",
    trustItems: [
      {title: "Sources you can inspect", body: "Journeys show their source links and review information. Check each journey’s disclosure: some starter guidance is still marked as awaiting expert verification."},
      {title: "AI explains and drafts", body: "AI helps interpret your question and explain the saved guidance. It can prepare a bilingual contribution for review. It cannot approve or publish that contribution."},
      {title: "People review changes", body: "Contributor drafts stay unpublished until the review requirements are met, including support from two distinct verified experts. Existing cases keep the exact version they started with."},
    ],
    reality: "What you can rely on today", available: "In this prototype", limits: "Its boundaries",
    works: ["Find a published journey and prepare for its next action.", "Record responses and follow supported recovery paths.", "Return to saved cases and prepare documents to take with you."],
    boundaries: ["Sahayak does not contact the government, your bank or an office, and does not submit grievances.", "AI answers may be unavailable. Saved instructions and explicit actions remain usable.", "Cases belong to this browser. Clearing its cookies or changing devices can prevent access; keep a copy of your brief."],
    demo: "Independent hackathon prototype. The example above is illustrative, not a verified citizen outcome. Use fictional details when trying the demo. Confirm current requirements with the linked official service.",
    ending: "Start with the problem in front of you.", endingBody: "You do not need to know the department, the acronym or the whole process.", footer: "Sahayak · Clear next steps for public-service problems",
  },
  hi: {
    label: "सहायक के बारे में", back: "मदद लें", title: "पोर्टल पर स्थिति दिखती है।\nआपको अगला कदम चाहिए।",
    intro: "छात्रवृत्ति जारी दिखाई दे रही है, लेकिन खाते में पैसा नहीं आया। किससे पूछें, क्या लेकर जाएँ, और अगर वे कहीं और भेज दें तो क्या करें?",
    principle: "दफ़्तरों की जगह नहीं। बेवजह चक्कर लगाने से राहत।",
    problem: "पूरी व्यवस्था की कड़ियाँ आपको अकेले नहीं जोड़नी चाहिए।",
    problemBody: "सरकारी काम अक्सर पोर्टल, बैंक और दफ़्तर के बीच बँटा होता है। हर जगह पूरी बात नहीं मिलती। सहायक अगला कदम, तैयारी और आगे की पूछताछ एक जगह रखता है, ताकि आप साफ़ सवाल लेकर सही जगह पहुँच सकें।",
    example: "एक उदाहरण, भुगतान मिलने का दावा नहीं", exampleTitle: "“छात्रवृत्ति जारी दिख रही है, पर पैसा नहीं आया।”",
    steps: [
      {title: "पहले समझें कि स्थिति का मतलब क्या है", body: "भुगतान का असली संदेश कहाँ देखें, यह जानें। शुरू करने के लिए PFMS का मतलब जानना या दफ़्तर का जवाब पहले से होना ज़रूरी नहीं है।"},
      {title: "तैयारी के साथ जाएँ", body: "कहाँ पूछना है, क्या ले जाना है, क्या कहना है और कौन-सी पावती लेनी है—यह देखें। कोई बात समझ न आए तो सहायक से पूछें।"},
      {title: "जो जवाब मिला, उसे दर्ज करें", body: "असली जवाब, तारीख और संदर्भ नंबर रखें। अगर बताई गई परेशानी के लिए यात्रा में रास्ता है—जैसे NPCI मैपिंग की समस्या—तो उससे जुड़ा अगला कदम खुलेगा।"},
      {title: "अपनी जगह और रिकॉर्ड सुरक्षित रखें", body: "इसी ब्राउज़र में लौटकर आगे बढ़ें। अगले कदम का सार और काम के दस्तावेज़ साथ रखें। जवाब सहेजने या मसौदा बनने का मतलब पैसा मिलना नहीं है।"},
    ],
    try: "अपना अगला कदम खोजें", tryNote: "होम पेज पर “छात्रवृत्ति का पैसा नहीं आया” चुनें या अपनी समस्या लिखें।",
    trustLabel: "मार्गदर्शन की जाँच कैसे होती है", trustTitle: "अनुभव से यात्रा सुधर सकती है। मंज़ूरी के लिए समीक्षा ज़रूरी है।",
    trustItems: [
      {title: "स्रोत खुद देख सकते हैं", body: "यात्राओं में स्रोत के लिंक और समीक्षा की जानकारी मिलती है। हर यात्रा का विवरण पढ़ें: कुछ शुरुआती मार्गदर्शन की विशेषज्ञ जाँच अभी बाकी है।"},
      {title: "AI समझाता है और मसौदा बनाता है", body: "AI आपके सवाल को समझने और सहेजे गए मार्गदर्शन को समझाने में मदद करता है। वह समीक्षा के लिए दो भाषाओं में योगदान का मसौदा बना सकता है, उसे मंज़ूर या प्रकाशित नहीं कर सकता।"},
      {title: "बदलाव की समीक्षा लोग करते हैं", body: "योगदान का मसौदा समीक्षा की शर्तें पूरी होने तक प्रकाशित नहीं होता। इनमें दो अलग सत्यापित विशेषज्ञों का समर्थन शामिल है। पुराने केस उसी संस्करण पर रहते हैं जिससे वे शुरू हुए थे।"},
    ],
    reality: "आज आप क्या कर सकते हैं", available: "इस प्रोटोटाइप में", limits: "इसकी सीमाएँ",
    works: ["प्रकाशित यात्रा खोजें और अगले कदम की तैयारी करें।", "जवाब दर्ज करें और उपलब्ध सुधार के रास्ते पर चलें।", "सहेजे गए केस पर लौटें और साथ ले जाने के लिए दस्तावेज़ तैयार करें।"],
    boundaries: ["सहायक सरकार, बैंक या दफ़्तर से संपर्क नहीं करता और शिकायत जमा नहीं करता।", "AI जवाब कभी उपलब्ध नहीं हो सकते। सहेजे निर्देश और सीधे बटन से किए जाने वाले काम फिर भी उपलब्ध रहते हैं।", "केस इसी ब्राउज़र से जुड़े हैं। कुकी मिटाने या डिवाइस बदलने से पहुँच खो सकती है; अपने सार की कॉपी रखें।"],
    demo: "स्वतंत्र हैकाथॉन प्रोटोटाइप। ऊपर दिया उदाहरण किसी सत्यापित नागरिक के सफल परिणाम का दावा नहीं है। डेमो में काल्पनिक जानकारी इस्तेमाल करें। मौजूदा ज़रूरतें दिए गए आधिकारिक सेवा लिंक से जाँचें।",
    ending: "अभी जिस काम में अटके हैं, वहीं से शुरू करें।", endingBody: "विभाग का नाम, छोटे नामों का मतलब या पूरी प्रक्रिया जानना ज़रूरी नहीं है।", footer: "सहायक · सरकारी काम के लिए साफ़ अगले कदम",
  },
};
